clone_folder: c:\projects\gears\string

init:
    - SET PATH=C:\Program Files\OpenSSL;c:\tools\php;%PATH%
    - SET COMPOSER_NO_INTERACTION=1
    - SET PHP=1
    - SET ANSICON=121x90 (121x90)

install:
  - cinst -y OpenSSL.Light
  - cinst -y php
  - cd c:\tools\php
  - copy php.ini-production php.ini /Y
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_fileinfo.dll >> php.ini
  - appveyor DownloadFile https://getcomposer.org/composer.phar -FileName composer

build_script:
    - cd c:\projects\gears\string
    - composer install

test_script:
  - cd c:\projects\gears\string
  - vendor\bin\robo test

deploy: off
